### model
model_name_or_path: Qwen/Qwen1.5-72B

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset: identity,alpaca_en_demo
template: qwen
cutoff_len: 8192
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/qwen1.5-72B/full/sft
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true
packing: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 128
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500
