### model
model_name_or_path: /AI-DATA/Models/Baichuan/Baichuan2-7B-Chat

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all
deepspeed: ../../examples/deepspeed/ds_z1_config.json
flash_attn: fa2

### dataset
dataset_dir: ../../data
dataset: alpaca_en_demo
cutoff_len: 4096
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16
template: default

### output
output_dir: ../../saves/baichuan2-7b/lora/pretrain
logging_steps: 10
save_steps: 5000000
plot_loss: true
overwrite_output_dir: true
include_tokens_per_second: true

### train
per_device_train_batch_size: 8
gradient_accumulation_steps: 2
learning_rate: 5.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500

