### model
model_name_or_path: /software/kanliu/chatglm3/chatglm3-6b/

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all
deepspeed: ../../examples/deepspeed/ds_z2_config.json

### dataset
dataset_dir: ../../data
dataset: identity,alpaca_en_demo
template: chatglm3
cutoff_len: 8192
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16
packing: true

### output
output_dir: /kanliu/chatglm3/chatglm3/output_lora
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 16
learning_rate: 1.0e-4
num_train_epochs: 500
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500
